### ISSUE TITLE
website: improved table design, incl. some filters / sorting

### ISSUE THREAD

**Issue by seabo** [hitsave-io/xyz#92]
Immediately achievable:
- [ ] every `fn_key` has its own collabsible accordion segment, which is a distinct table
- [ ] in the table header is a list of arguments (maybe with a histogram) 
- [ ] each argument has a checkbox which causes it to appear as a column in the table
- [ ] table state is stored in local storage / maybe the server

Bigger effort (requires porting Ed's Sqlite proof-of-concept to Postgres and implementing `/binding` route
- [ ] another part of the header is a list of the different function hashes, and you can use these to filter by function hash
- [ ] you can click on pairs of function hashes, and it shows a diff of them
- [ ] tells you the dependencies of the function
